server:
  port: 18100
spring:
  application:
    name: demo-user-provider-server
eureka:
  client:
    serviceUrl:
      # 注册到集群，就把多个Eureka server地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://eurekaServer1:18061/eureka,http://eurekaServer2:18062/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）